# This is a generated file. Not intended for manual editing.
services:
  web.api:
    build:
      context: "C:\\Users\\Otavio\\RiderProjects\\KeycloakAuthIntegration"
      dockerfile: "src/KeycloakAuthIntegration.WebApi/Dockerfile"
      target: "base"
    command: []
    entrypoint:
    - "dotnet"
    - "/app/bin/Debug/net8.0/KeycloakAuthIntegration.WebApi.dll"
    environment:
      DOTNET_USE_POLLING_FILE_WATCHER: "true"
    image: "webapi:dev"
    ports: []
    volumes:
    - "C:\\Users\\Otavio\\RiderProjects\\KeycloakAuthIntegration\\src\\KeycloakAuthIntegration.WebApi:/app:rw"
    - "C:\\Users\\Otavio\\RiderProjects\\KeycloakAuthIntegration:/src:rw"
    - "C:\\Users\\Otavio\\.nuget\\packages:/home/app/.nuget/packages"
    working_dir: "/app"
